name: order_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  client_repository:
    path: ../client_repository
  fabric_repository:
    path: ../fabric_repository
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: